name: Ruff

on:
  pull_request:
    branches:
      - master

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ruff lint
        uses: chartboost/ruff-action@v1
        with:
          args: check .